### ISSUE TITLE
Anvil usage warning (when using default chainid)

### ISSUE THREAD

**Issue by ualtinok** [radeksvarz/createx-forge#1]
It would be great if we can put a warning for the behaviour of usage in local tesnet (anvil).

**Comment by radeksvarz** [comment]
What do you mean? Can you pls demonstrate the example?

**Comment by ualtinok** [comment]
I was trying to deploy contracts to anvil yesterday and even though createx computed and returned correct addresses from create3, deployed contracts were on different addresses. Finally I found this comment inside DeployExampleCounter.s.sol

https://github.com/radeksvarz/createx-forge/blob/c033dd357340c04dcdab1e1335dc5bcdce153d19/script/DeployExampleCounter.s.sol#L19

```
// WARNING - etching is not supported towards local explicit Anvil execution with default chainID
//      This leads to a strange behaviour towards Anvil when Anvil does not have CreateX predeployed
//      (seamingly correct transactions in the forge simulation even when broadcasted).
//      Start Anvil with a different chainID, e.g. `anvil --chain-id 1982` to simulate a correct behaviour
//      of missing CreateX.
// 
```

So I assumed this was the reason. If this is unrelated to my problem, I can create an example repo.

**Comment by radeksvarz** [comment]
yep, it's mentioned in the README: https://github.com/radeksvarz/createx-forge?tab=readme-ov-file#detection-does-not-work-with-explicit-local-anvil

The part of the root cause is the detection of the Foundry testing environment - Foundry uses anvil "internally" for tests with the chainid 31337. The same when you start Anvil "externally" and point RPC towards localhost.
https://github.com/radeksvarz/createx-forge/blob/c033dd357340c04dcdab1e1335dc5bcdce153d19/script/CreateXScript.sol#L70

Have you tried to run anvil with different chainid as instructed?

**Comment by ualtinok** [comment]
Oh! I'm sorry missed that part in the FAQ. It still didn't work when I used a different chainid for anvil. I can try to send a small repro.

**Comment by radeksvarz** [comment]
> It still didn't work when I used a different chainid for anvil.

This is strange. Example repo would help.

**Comment by radeksvarz** [comment]
added the instruction how to work with local Anvil:
https://github.com/radeksvarz/createx-forge?tab=readme-ov-file#how-to-use-it-with-local-anvil
